// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: cronova/worker/v1/worker.proto

package workerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkerHub_Session_FullMethodName = "/cronova.worker.v1.WorkerHub/Session"
)

// WorkerHubClient is the client API for WorkerHub service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WorkerHub is the scheduler-side service a remote worker DIALS INTO. The
// direction is deliberately inverted from the legacy Executor service: the
// worker needs no reachable address, no open inbound port, and traverses NAT —
// it joins with a one-time token (HTTP, see /api/workers/join), receives an
// mTLS client certificate, and then holds one long-lived bidirectional Session
// stream over which everything flows: assignments, cancels, task events,
// heartbeats, and task log bytes.
//
// Tasks themselves are executed by the same Runner the standalone executor
// uses (attempt state on disk, process-group re-adoption on worker restart),
// so a worker process restart does NOT kill or re-run its tasks.
type WorkerHubClient interface {
	// Session is the worker's single connection. First message MUST be Hello;
	// the server answers HelloAck (or terminates the stream with an error).
	// Either side closing the stream ends the session; the worker reconnects
	// with backoff and resumes log streaming from the last acknowledged offset.
	Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WorkerMessage, ServerMessage], error)
}

type workerHubClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerHubClient(cc grpc.ClientConnInterface) WorkerHubClient {
	return &workerHubClient{cc}
}

func (c *workerHubClient) Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WorkerMessage, ServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkerHub_ServiceDesc.Streams[0], WorkerHub_Session_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WorkerMessage, ServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerHub_SessionClient = grpc.BidiStreamingClient[WorkerMessage, ServerMessage]

// WorkerHubServer is the server API for WorkerHub service.
// All implementations must embed UnimplementedWorkerHubServer
// for forward compatibility.
//
// WorkerHub is the scheduler-side service a remote worker DIALS INTO. The
// direction is deliberately inverted from the legacy Executor service: the
// worker needs no reachable address, no open inbound port, and traverses NAT —
// it joins with a one-time token (HTTP, see /api/workers/join), receives an
// mTLS client certificate, and then holds one long-lived bidirectional Session
// stream over which everything flows: assignments, cancels, task events,
// heartbeats, and task log bytes.
//
// Tasks themselves are executed by the same Runner the standalone executor
// uses (attempt state on disk, process-group re-adoption on worker restart),
// so a worker process restart does NOT kill or re-run its tasks.
type WorkerHubServer interface {
	// Session is the worker's single connection. First message MUST be Hello;
	// the server answers HelloAck (or terminates the stream with an error).
	// Either side closing the stream ends the session; the worker reconnects
	// with backoff and resumes log streaming from the last acknowledged offset.
	Session(grpc.BidiStreamingServer[WorkerMessage, ServerMessage]) error
	mustEmbedUnimplementedWorkerHubServer()
}

// UnimplementedWorkerHubServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkerHubServer struct{}

func (UnimplementedWorkerHubServer) Session(grpc.BidiStreamingServer[WorkerMessage, ServerMessage]) error {
	return status.Error(codes.Unimplemented, "method Session not implemented")
}
func (UnimplementedWorkerHubServer) mustEmbedUnimplementedWorkerHubServer() {}
func (UnimplementedWorkerHubServer) testEmbeddedByValue()                   {}

// UnsafeWorkerHubServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerHubServer will
// result in compilation errors.
type UnsafeWorkerHubServer interface {
	mustEmbedUnimplementedWorkerHubServer()
}

func RegisterWorkerHubServer(s grpc.ServiceRegistrar, srv WorkerHubServer) {
	// If the following call panics, it indicates UnimplementedWorkerHubServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkerHub_ServiceDesc, srv)
}

func _WorkerHub_Session_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WorkerHubServer).Session(&grpc.GenericServerStream[WorkerMessage, ServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerHub_SessionServer = grpc.BidiStreamingServer[WorkerMessage, ServerMessage]

// WorkerHub_ServiceDesc is the grpc.ServiceDesc for WorkerHub service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkerHub_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cronova.worker.v1.WorkerHub",
	HandlerType: (*WorkerHubServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Session",
			Handler:       _WorkerHub_Session_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "cronova/worker/v1/worker.proto",
}
