// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: cronova/worker/v1/worker.proto

package workerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Phase int32

const (
	Phase_PHASE_UNSPECIFIED Phase = 0
	Phase_PHASE_RUNNING     Phase = 1
	Phase_PHASE_EXITED      Phase = 2
	Phase_PHASE_UNKNOWN     Phase = 3 // worker has no record of the ref
)

// Enum value maps for Phase.
var (
	Phase_name = map[int32]string{
		0: "PHASE_UNSPECIFIED",
		1: "PHASE_RUNNING",
		2: "PHASE_EXITED",
		3: "PHASE_UNKNOWN",
	}
	Phase_value = map[string]int32{
		"PHASE_UNSPECIFIED": 0,
		"PHASE_RUNNING":     1,
		"PHASE_EXITED":      2,
		"PHASE_UNKNOWN":     3,
	}
)

func (x Phase) Enum() *Phase {
	p := new(Phase)
	*p = x
	return p
}

func (x Phase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Phase) Descriptor() protoreflect.EnumDescriptor {
	return file_cronova_worker_v1_worker_proto_enumTypes[0].Descriptor()
}

func (Phase) Type() protoreflect.EnumType {
	return &file_cronova_worker_v1_worker_proto_enumTypes[0]
}

func (x Phase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Phase.Descriptor instead.
func (Phase) EnumDescriptor() ([]byte, []int) {
	return file_cronova_worker_v1_worker_proto_rawDescGZIP(), []int{0}
}

type WorkerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*WorkerMessage_Hello
	//	*WorkerMessage_Heartbeat
	//	*WorkerMessage_TaskEvent
	//	*WorkerMessage_LogChunk
	Msg           isWorkerMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerMessage) Reset() {
	*x = WorkerMessage{}
	mi := &file_cronova_worker_v1_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerMessage) ProtoMessage() {}

func (x *WorkerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cronova_worker_v1_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerMessage.ProtoReflect.Descriptor instead.
func (*WorkerMessage) Descriptor() ([]byte, []int) {
	return file_cronova_worker_v1_worker_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerMessage) GetMsg() isWorkerMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *WorkerMessage) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Msg.(*WorkerMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *WorkerMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Msg.(*WorkerMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *WorkerMessage) GetTaskEvent() *TaskEvent {
	if x != nil {
		if x, ok := x.Msg.(*WorkerMessage_TaskEvent); ok {
			return x.TaskEvent
		}
	}
	return nil
}

func (x *WorkerMessage) GetLogChunk() *LogChunk {
	if x != nil {
		if x, ok := x.Msg.(*WorkerMessage_LogChunk); ok {
			return x.LogChunk
		}
	}
	return nil
}

type isWorkerMessage_Msg interface {
	isWorkerMessage_Msg()
}

type WorkerMessage_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type WorkerMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type WorkerMessage_TaskEvent struct {
	TaskEvent *TaskEvent `protobuf:"bytes,3,opt,name=task_event,json=taskEvent,proto3,oneof"`
}

type WorkerMessage_LogChunk struct {
	LogChunk *LogChunk `protobuf:"bytes,4,opt,name=log_chunk,json=logChunk,proto3,oneof"`
}

func (*WorkerMessage_Hello) isWorkerMessage_Msg() {}

func (*WorkerMessage_Heartbeat) isWorkerMessage_Msg() {}

func (*WorkerMessage_TaskEvent) isWorkerMessage_Msg() {}

func (*WorkerMessage_LogChunk) isWorkerMessage_Msg() {}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ServerMessage_HelloAck
	//	*ServerMessage_Assign
	//	*ServerMessage_Cancel
	//	*ServerMessage_Probe
	//	*ServerMessage_LogAck
	Msg           isServerMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_cronova_worker_v1_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cronova_worker_v1_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_cronova_worker_v1_worker_proto_rawDescGZIP(), []int{1}
}

func (x *ServerMessage) GetMsg() isServerMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ServerMessage) GetHelloAck() *HelloAck {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_HelloAck); ok {
			return x.HelloAck
		}
	}
	return nil
}

func (x *ServerMessage) GetAssign() *Assign {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_Assign); ok {
			return x.Assign
		}
	}
	return nil
}

func (x *ServerMessage) GetCancel() *Cancel {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

func (x *ServerMessage) GetProbe() *Probe {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_Probe); ok {
			return x.Probe
		}
	}
	return nil
}

func (x *ServerMessage) GetLogAck() *LogAck {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_LogAck); ok {
			return x.LogAck
		}
	}
	return nil
}

type isServerMessage_Msg interface {
	isServerMessage_Msg()
}

type ServerMessage_HelloAck struct {
	HelloAck *HelloAck `protobuf:"bytes,1,opt,name=hello_ack,json=helloAck,proto3,oneof"`
}

type ServerMessage_Assign struct {
	Assign *Assign `protobuf:"bytes,2,opt,name=assign,proto3,oneof"`
}

type ServerMessage_Cancel struct {
	Cancel *Cancel `protobuf:"bytes,3,opt,name=cancel,proto3,oneof"`
}

type ServerMessage_Probe struct {
	Probe *Probe `protobuf:"bytes,4,opt,name=probe,proto3,oneof"`
}

type ServerMessage_LogAck struct {
	LogAck *LogAck `protobuf:"bytes,5,opt,name=log_ack,json=logAck,proto3,oneof"`
}

func (*ServerMessage_HelloAck) isServerMessage_Msg() {}

func (*ServerMessage_Assign) isServerMessage_Msg() {}

func (*ServerMessage_Cancel) isServerMessage_Msg() {}

func (*ServerMessage_Probe) isServerMessage_Msg() {}

func (*ServerMessage_LogAck) isServerMessage_Msg() {}

// Hello identifies the (already certificate-authenticated) worker and declares
// what it is still running, so the scheduler can re-adopt in-flight attempts
// after either side restarted instead of double-launching them.
type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"` // issued at join; must match the client certificate CN
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // includes "group" (worker group), default "default"
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`                                                                         // worker binary version
	ActiveRefs    []string               `protobuf:"bytes,5,rep,name=active_refs,json=activeRefs,proto3" json:"active_refs,omitempty"`                                                 // attempt refs still running locally
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_cronova_worker_v1_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_cronova_worker_v1_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_cronova_worker_v1_worker_proto_rawDescGZIP(), []int{2}
}

func (x *Hello) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *Hello) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Hello) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Hello) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Hello) GetActiveRefs() []string {
	if x != nil {
		return x.ActiveRefs
	}
	return nil
}

type HelloAck struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	HeartbeatSeconds int64                  `protobuf:"varint,1,opt,name=heartbeat_seconds,json=heartbeatSeconds,proto3" json:"heartbeat_seconds,omitempty"` // interval the server expects
	ServerUnixMs     int64                  `protobuf:"varint,2,opt,name=server_unix_ms,json=serverUnixMs,proto3" json:"server_unix_ms,omitempty"`           // rough clock cross-check for log timestamps
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HelloAck) Reset() {
	*x = HelloAck{}
	mi := &file_cronova_worker_v1_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloAck) ProtoMessage() {}

func (x *HelloAck) ProtoReflect() protoreflect.Message {
	mi := &file_cronova_worker_v1_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloAck.ProtoReflect.Descriptor instead.
func (*HelloAck) Descriptor() ([]byte, []int) {
	return file_cronova_worker_v1_worker_proto_rawDescGZIP(), []int{3}
}

func (x *HelloAck) GetHeartbeatSeconds() int64 {
	if x != nil {
		return x.HeartbeatSeconds
	}
	return 0
}

func (x *HelloAck) GetServerUnixMs() int64 {
	if x != nil {
		return x.ServerUnixMs
	}
	return 0
}

// Heartbeat doubles as the load report used by least-active-tasks routing.
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActiveTasks   int32                  `protobuf:"varint,1,opt,name=active_tasks,json=activeTasks,proto3" json:"active_tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_cronova_worker_v1_worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_cronova_worker_v1_worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_cronova_worker_v1_worker_proto_rawDescGZIP(), []int{4}
}

func (x *Heartbeat) GetActiveTasks() int32 {
	if x != nil {
		return x.ActiveTasks
	}
	return 0
}

// Assign launches a task on the worker (idempotent on ref, same contract as
// the legacy Launch). Logs are NOT written to a shared path — the worker
// spools locally and streams LogChunks back.
type Assign struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Ref            string                 `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`   // run_id/task_id/try — idempotency key
	Type           string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // shell/python/sql/jar/http (informational)
	Command        string                 `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	Env            map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TimeoutSeconds int64                  `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	Redact         []string               `protobuf:"bytes,6,rep,name=redact,proto3" json:"redact,omitempty"` // secret values to mask from everything logged
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Assign) Reset() {
	*x = Assign{}
	mi := &file_cronova_worker_v1_worker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Assign) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Assign) ProtoMessage() {}

func (x *Assign) ProtoReflect() protoreflect.Message {
	mi := &file_cronova_worker_v1_worker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Assign.ProtoReflect.Descriptor instead.
func (*Assign) Descriptor() ([]byte, []int) {
	return file_cronova_worker_v1_worker_proto_rawDescGZIP(), []int{5}
}

func (x *Assign) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *Assign) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Assign) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Assign) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *Assign) GetTimeoutSeconds() int64 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *Assign) GetRedact() []string {
	if x != nil {
		return x.Redact
	}
	return nil
}

type Cancel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           string                 `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cancel) Reset() {
	*x = Cancel{}
	mi := &file_cronova_worker_v1_worker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cancel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cancel) ProtoMessage() {}

func (x *Cancel) ProtoReflect() protoreflect.Message {
	mi := &file_cronova_worker_v1_worker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cancel.ProtoReflect.Descriptor instead.
func (*Cancel) Descriptor() ([]byte, []int) {
	return file_cronova_worker_v1_worker_proto_rawDescGZIP(), []int{6}
}

func (x *Cancel) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

// Probe asks the worker to re-report a ref's state via a TaskEvent — used by
// scheduler recovery when an awaited task's terminal event may have been lost
// in a disconnect.
type Probe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           string                 `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Probe) Reset() {
	*x = Probe{}
	mi := &file_cronova_worker_v1_worker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Probe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Probe) ProtoMessage() {}

func (x *Probe) ProtoReflect() protoreflect.Message {
	mi := &file_cronova_worker_v1_worker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Probe.ProtoReflect.Descriptor instead.
func (*Probe) Descriptor() ([]byte, []int) {
	return file_cronova_worker_v1_worker_proto_rawDescGZIP(), []int{7}
}

func (x *Probe) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

// TaskEvent reports an attempt's lifecycle transition (or Probe answer).
type TaskEvent struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Ref         string                 `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Phase       Phase                  `protobuf:"varint,2,opt,name=phase,proto3,enum=cronova.worker.v1.Phase" json:"phase,omitempty"`
	ExitCode    int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`         // valid when phase = PHASE_EXITED; 124 = timeout kill
	LaunchError string                 `protobuf:"bytes,4,opt,name=launch_error,json=launchError,proto3" json:"launch_error,omitempty"` // set when the process could not be started at all
	// output carries the task's $CRONOVA_OUTPUT file (small JSON string map,
	// <= 64 KiB) on exit, so {{ ti.<task>.<key> }} works for remote tasks whose
	// filesystem the scheduler cannot read.
	Output        []byte `protobuf:"bytes,5,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskEvent) Reset() {
	*x = TaskEvent{}
	mi := &file_cronova_worker_v1_worker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskEvent) ProtoMessage() {}

func (x *TaskEvent) ProtoReflect() protoreflect.Message {
	mi := &file_cronova_worker_v1_worker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskEvent.ProtoReflect.Descriptor instead.
func (*TaskEvent) Descriptor() ([]byte, []int) {
	return file_cronova_worker_v1_worker_proto_rawDescGZIP(), []int{8}
}

func (x *TaskEvent) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *TaskEvent) GetPhase() Phase {
	if x != nil {
		return x.Phase
	}
	return Phase_PHASE_UNSPECIFIED
}

func (x *TaskEvent) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *TaskEvent) GetLaunchError() string {
	if x != nil {
		return x.LaunchError
	}
	return ""
}

func (x *TaskEvent) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

// LogChunk streams task output. offset is the byte position of data[0] in the
// task's combined stdout+stderr stream; the server appends in order, ignores
// chunks at or below its high-water mark (resend-safe), and periodically
// answers with LogAck so the worker can trim its local spool.
type LogChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           string                 `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Eof           bool                   `protobuf:"varint,4,opt,name=eof,proto3" json:"eof,omitempty"` // no more bytes will follow for this ref
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogChunk) Reset() {
	*x = LogChunk{}
	mi := &file_cronova_worker_v1_worker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogChunk) ProtoMessage() {}

func (x *LogChunk) ProtoReflect() protoreflect.Message {
	mi := &file_cronova_worker_v1_worker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogChunk.ProtoReflect.Descriptor instead.
func (*LogChunk) Descriptor() ([]byte, []int) {
	return file_cronova_worker_v1_worker_proto_rawDescGZIP(), []int{9}
}

func (x *LogChunk) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *LogChunk) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *LogChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *LogChunk) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

type LogAck struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Ref    string                 `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Offset int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"` // durable through this byte count
	// rewind demands the worker restart streaming from offset (the hub found a
	// gap — e.g. its log file was pruned while the worker kept spooling). A
	// plain ack never moves the worker's cursor backward; only rewind does.
	Rewind        bool `protobuf:"varint,3,opt,name=rewind,proto3" json:"rewind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogAck) Reset() {
	*x = LogAck{}
	mi := &file_cronova_worker_v1_worker_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogAck) ProtoMessage() {}

func (x *LogAck) ProtoReflect() protoreflect.Message {
	mi := &file_cronova_worker_v1_worker_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogAck.ProtoReflect.Descriptor instead.
func (*LogAck) Descriptor() ([]byte, []int) {
	return file_cronova_worker_v1_worker_proto_rawDescGZIP(), []int{10}
}

func (x *LogAck) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *LogAck) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *LogAck) GetRewind() bool {
	if x != nil {
		return x.Rewind
	}
	return false
}

var File_cronova_worker_v1_worker_proto protoreflect.FileDescriptor

const file_cronova_worker_v1_worker_proto_rawDesc = "" +
	"\n" +
	"\x1ecronova/worker/v1/worker.proto\x12\x11cronova.worker.v1\"\x81\x02\n" +
	"\rWorkerMessage\x120\n" +
	"\x05hello\x18\x01 \x01(\v2\x18.cronova.worker.v1.HelloH\x00R\x05hello\x12<\n" +
	"\theartbeat\x18\x02 \x01(\v2\x1c.cronova.worker.v1.HeartbeatH\x00R\theartbeat\x12=\n" +
	"\n" +
	"task_event\x18\x03 \x01(\v2\x1c.cronova.worker.v1.TaskEventH\x00R\ttaskEvent\x12:\n" +
	"\tlog_chunk\x18\x04 \x01(\v2\x1b.cronova.worker.v1.LogChunkH\x00R\blogChunkB\x05\n" +
	"\x03msg\"\xa4\x02\n" +
	"\rServerMessage\x12:\n" +
	"\thello_ack\x18\x01 \x01(\v2\x1b.cronova.worker.v1.HelloAckH\x00R\bhelloAck\x123\n" +
	"\x06assign\x18\x02 \x01(\v2\x19.cronova.worker.v1.AssignH\x00R\x06assign\x123\n" +
	"\x06cancel\x18\x03 \x01(\v2\x19.cronova.worker.v1.CancelH\x00R\x06cancel\x120\n" +
	"\x05probe\x18\x04 \x01(\v2\x18.cronova.worker.v1.ProbeH\x00R\x05probe\x124\n" +
	"\alog_ack\x18\x05 \x01(\v2\x19.cronova.worker.v1.LogAckH\x00R\x06logAckB\x05\n" +
	"\x03msg\"\xec\x01\n" +
	"\x05Hello\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12<\n" +
	"\x06labels\x18\x03 \x03(\v2$.cronova.worker.v1.Hello.LabelsEntryR\x06labels\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x1f\n" +
	"\vactive_refs\x18\x05 \x03(\tR\n" +
	"activeRefs\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"]\n" +
	"\bHelloAck\x12+\n" +
	"\x11heartbeat_seconds\x18\x01 \x01(\x03R\x10heartbeatSeconds\x12$\n" +
	"\x0eserver_unix_ms\x18\x02 \x01(\x03R\fserverUnixMs\".\n" +
	"\tHeartbeat\x12!\n" +
	"\factive_tasks\x18\x01 \x01(\x05R\vactiveTasks\"\xf7\x01\n" +
	"\x06Assign\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\tR\x03ref\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\x124\n" +
	"\x03env\x18\x04 \x03(\v2\".cronova.worker.v1.Assign.EnvEntryR\x03env\x12'\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\x03R\x0etimeoutSeconds\x12\x16\n" +
	"\x06redact\x18\x06 \x03(\tR\x06redact\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x1a\n" +
	"\x06Cancel\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\tR\x03ref\"\x19\n" +
	"\x05Probe\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\tR\x03ref\"\xa5\x01\n" +
	"\tTaskEvent\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\tR\x03ref\x12.\n" +
	"\x05phase\x18\x02 \x01(\x0e2\x18.cronova.worker.v1.PhaseR\x05phase\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12!\n" +
	"\flaunch_error\x18\x04 \x01(\tR\vlaunchError\x12\x16\n" +
	"\x06output\x18\x05 \x01(\fR\x06output\"Z\n" +
	"\bLogChunk\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\tR\x03ref\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x10\n" +
	"\x03eof\x18\x04 \x01(\bR\x03eof\"J\n" +
	"\x06LogAck\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\tR\x03ref\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x16\n" +
	"\x06rewind\x18\x03 \x01(\bR\x06rewind*V\n" +
	"\x05Phase\x12\x15\n" +
	"\x11PHASE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rPHASE_RUNNING\x10\x01\x12\x10\n" +
	"\fPHASE_EXITED\x10\x02\x12\x11\n" +
	"\rPHASE_UNKNOWN\x10\x032^\n" +
	"\tWorkerHub\x12Q\n" +
	"\aSession\x12 .cronova.worker.v1.WorkerMessage\x1a .cronova.worker.v1.ServerMessage(\x010\x01B<Z:github.com/zoyluo/cronova/proto/cronova/worker/v1;workerv1b\x06proto3"

var (
	file_cronova_worker_v1_worker_proto_rawDescOnce sync.Once
	file_cronova_worker_v1_worker_proto_rawDescData []byte
)

func file_cronova_worker_v1_worker_proto_rawDescGZIP() []byte {
	file_cronova_worker_v1_worker_proto_rawDescOnce.Do(func() {
		file_cronova_worker_v1_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cronova_worker_v1_worker_proto_rawDesc), len(file_cronova_worker_v1_worker_proto_rawDesc)))
	})
	return file_cronova_worker_v1_worker_proto_rawDescData
}

var file_cronova_worker_v1_worker_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cronova_worker_v1_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_cronova_worker_v1_worker_proto_goTypes = []any{
	(Phase)(0),            // 0: cronova.worker.v1.Phase
	(*WorkerMessage)(nil), // 1: cronova.worker.v1.WorkerMessage
	(*ServerMessage)(nil), // 2: cronova.worker.v1.ServerMessage
	(*Hello)(nil),         // 3: cronova.worker.v1.Hello
	(*HelloAck)(nil),      // 4: cronova.worker.v1.HelloAck
	(*Heartbeat)(nil),     // 5: cronova.worker.v1.Heartbeat
	(*Assign)(nil),        // 6: cronova.worker.v1.Assign
	(*Cancel)(nil),        // 7: cronova.worker.v1.Cancel
	(*Probe)(nil),         // 8: cronova.worker.v1.Probe
	(*TaskEvent)(nil),     // 9: cronova.worker.v1.TaskEvent
	(*LogChunk)(nil),      // 10: cronova.worker.v1.LogChunk
	(*LogAck)(nil),        // 11: cronova.worker.v1.LogAck
	nil,                   // 12: cronova.worker.v1.Hello.LabelsEntry
	nil,                   // 13: cronova.worker.v1.Assign.EnvEntry
}
var file_cronova_worker_v1_worker_proto_depIdxs = []int32{
	3,  // 0: cronova.worker.v1.WorkerMessage.hello:type_name -> cronova.worker.v1.Hello
	5,  // 1: cronova.worker.v1.WorkerMessage.heartbeat:type_name -> cronova.worker.v1.Heartbeat
	9,  // 2: cronova.worker.v1.WorkerMessage.task_event:type_name -> cronova.worker.v1.TaskEvent
	10, // 3: cronova.worker.v1.WorkerMessage.log_chunk:type_name -> cronova.worker.v1.LogChunk
	4,  // 4: cronova.worker.v1.ServerMessage.hello_ack:type_name -> cronova.worker.v1.HelloAck
	6,  // 5: cronova.worker.v1.ServerMessage.assign:type_name -> cronova.worker.v1.Assign
	7,  // 6: cronova.worker.v1.ServerMessage.cancel:type_name -> cronova.worker.v1.Cancel
	8,  // 7: cronova.worker.v1.ServerMessage.probe:type_name -> cronova.worker.v1.Probe
	11, // 8: cronova.worker.v1.ServerMessage.log_ack:type_name -> cronova.worker.v1.LogAck
	12, // 9: cronova.worker.v1.Hello.labels:type_name -> cronova.worker.v1.Hello.LabelsEntry
	13, // 10: cronova.worker.v1.Assign.env:type_name -> cronova.worker.v1.Assign.EnvEntry
	0,  // 11: cronova.worker.v1.TaskEvent.phase:type_name -> cronova.worker.v1.Phase
	1,  // 12: cronova.worker.v1.WorkerHub.Session:input_type -> cronova.worker.v1.WorkerMessage
	2,  // 13: cronova.worker.v1.WorkerHub.Session:output_type -> cronova.worker.v1.ServerMessage
	13, // [13:14] is the sub-list for method output_type
	12, // [12:13] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_cronova_worker_v1_worker_proto_init() }
func file_cronova_worker_v1_worker_proto_init() {
	if File_cronova_worker_v1_worker_proto != nil {
		return
	}
	file_cronova_worker_v1_worker_proto_msgTypes[0].OneofWrappers = []any{
		(*WorkerMessage_Hello)(nil),
		(*WorkerMessage_Heartbeat)(nil),
		(*WorkerMessage_TaskEvent)(nil),
		(*WorkerMessage_LogChunk)(nil),
	}
	file_cronova_worker_v1_worker_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerMessage_HelloAck)(nil),
		(*ServerMessage_Assign)(nil),
		(*ServerMessage_Cancel)(nil),
		(*ServerMessage_Probe)(nil),
		(*ServerMessage_LogAck)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cronova_worker_v1_worker_proto_rawDesc), len(file_cronova_worker_v1_worker_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cronova_worker_v1_worker_proto_goTypes,
		DependencyIndexes: file_cronova_worker_v1_worker_proto_depIdxs,
		EnumInfos:         file_cronova_worker_v1_worker_proto_enumTypes,
		MessageInfos:      file_cronova_worker_v1_worker_proto_msgTypes,
	}.Build()
	File_cronova_worker_v1_worker_proto = out.File
	file_cronova_worker_v1_worker_proto_goTypes = nil
	file_cronova_worker_v1_worker_proto_depIdxs = nil
}
