// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: cronova/executor/v1/executor.proto

package executorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Phase int32

const (
	Phase_PHASE_UNSPECIFIED Phase = 0
	Phase_PHASE_RUNNING     Phase = 1 // still executing
	Phase_PHASE_EXITED      Phase = 2 // finished; exit_code is valid
	Phase_PHASE_UNKNOWN     Phase = 3 // executor has no record (never launched, or executor restarted)
)

// Enum value maps for Phase.
var (
	Phase_name = map[int32]string{
		0: "PHASE_UNSPECIFIED",
		1: "PHASE_RUNNING",
		2: "PHASE_EXITED",
		3: "PHASE_UNKNOWN",
	}
	Phase_value = map[string]int32{
		"PHASE_UNSPECIFIED": 0,
		"PHASE_RUNNING":     1,
		"PHASE_EXITED":      2,
		"PHASE_UNKNOWN":     3,
	}
)

func (x Phase) Enum() *Phase {
	p := new(Phase)
	*p = x
	return p
}

func (x Phase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Phase) Descriptor() protoreflect.EnumDescriptor {
	return file_cronova_executor_v1_executor_proto_enumTypes[0].Descriptor()
}

func (Phase) Type() protoreflect.EnumType {
	return &file_cronova_executor_v1_executor_proto_enumTypes[0]
}

func (x Phase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Phase.Descriptor instead.
func (Phase) EnumDescriptor() ([]byte, []int) {
	return file_cronova_executor_v1_executor_proto_rawDescGZIP(), []int{0}
}

type LaunchRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskRunId      string                 `protobuf:"bytes,1,opt,name=task_run_id,json=taskRunId,proto3" json:"task_run_id,omitempty"` // run_id + "/" + task_id; the idempotency key and ref
	Type           string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`                              // shell/python/sql/jar (informational)
	Command        string                 `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`                        // shell command line
	Env            map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TimeoutSeconds int64                  `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"` // 0 = no timeout
	LogPath        string                 `protobuf:"bytes,6,opt,name=log_path,json=logPath,proto3" json:"log_path,omitempty"`                       // file for combined stdout/stderr
	// dir is the working directory the command runs in (cmd.Dir). Empty = inherit
	// the executor's cwd. Used to run an uploaded project's `python3 main.py` from
	// its staged directory. Assumes a filesystem shared with the scheduler that
	// staged it (same-host / shared mount) — the same assumption log_path makes.
	Dir           string `protobuf:"bytes,7,opt,name=dir,proto3" json:"dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LaunchRequest) Reset() {
	*x = LaunchRequest{}
	mi := &file_cronova_executor_v1_executor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LaunchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaunchRequest) ProtoMessage() {}

func (x *LaunchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cronova_executor_v1_executor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaunchRequest.ProtoReflect.Descriptor instead.
func (*LaunchRequest) Descriptor() ([]byte, []int) {
	return file_cronova_executor_v1_executor_proto_rawDescGZIP(), []int{0}
}

func (x *LaunchRequest) GetTaskRunId() string {
	if x != nil {
		return x.TaskRunId
	}
	return ""
}

func (x *LaunchRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LaunchRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *LaunchRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *LaunchRequest) GetTimeoutSeconds() int64 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *LaunchRequest) GetLogPath() string {
	if x != nil {
		return x.LogPath
	}
	return ""
}

func (x *LaunchRequest) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

type LaunchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           string                 `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"` // handle for Probe/Cancel; equals task_run_id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LaunchResponse) Reset() {
	*x = LaunchResponse{}
	mi := &file_cronova_executor_v1_executor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LaunchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaunchResponse) ProtoMessage() {}

func (x *LaunchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cronova_executor_v1_executor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaunchResponse.ProtoReflect.Descriptor instead.
func (*LaunchResponse) Descriptor() ([]byte, []int) {
	return file_cronova_executor_v1_executor_proto_rawDescGZIP(), []int{1}
}

func (x *LaunchResponse) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

type ProbeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           string                 `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeRequest) Reset() {
	*x = ProbeRequest{}
	mi := &file_cronova_executor_v1_executor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeRequest) ProtoMessage() {}

func (x *ProbeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cronova_executor_v1_executor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeRequest.ProtoReflect.Descriptor instead.
func (*ProbeRequest) Descriptor() ([]byte, []int) {
	return file_cronova_executor_v1_executor_proto_rawDescGZIP(), []int{2}
}

func (x *ProbeRequest) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

type ProbeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phase         Phase                  `protobuf:"varint,1,opt,name=phase,proto3,enum=cronova.executor.v1.Phase" json:"phase,omitempty"`
	ExitCode      int32                  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"` // valid when phase = PHASE_EXITED; 124 indicates timeout kill
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeResponse) Reset() {
	*x = ProbeResponse{}
	mi := &file_cronova_executor_v1_executor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeResponse) ProtoMessage() {}

func (x *ProbeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cronova_executor_v1_executor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeResponse.ProtoReflect.Descriptor instead.
func (*ProbeResponse) Descriptor() ([]byte, []int) {
	return file_cronova_executor_v1_executor_proto_rawDescGZIP(), []int{3}
}

func (x *ProbeResponse) GetPhase() Phase {
	if x != nil {
		return x.Phase
	}
	return Phase_PHASE_UNSPECIFIED
}

func (x *ProbeResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

type CancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           string                 `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_cronova_executor_v1_executor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cronova_executor_v1_executor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_cronova_executor_v1_executor_proto_rawDescGZIP(), []int{4}
}

func (x *CancelRequest) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

type CancelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelResponse) Reset() {
	*x = CancelResponse{}
	mi := &file_cronova_executor_v1_executor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelResponse) ProtoMessage() {}

func (x *CancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cronova_executor_v1_executor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelResponse.ProtoReflect.Descriptor instead.
func (*CancelResponse) Descriptor() ([]byte, []int) {
	return file_cronova_executor_v1_executor_proto_rawDescGZIP(), []int{5}
}

func (x *CancelResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_cronova_executor_v1_executor_proto protoreflect.FileDescriptor

const file_cronova_executor_v1_executor_proto_rawDesc = "" +
	"\n" +
	"\"cronova/executor/v1/executor.proto\x12\x13cronova.executor.v1\"\xaa\x02\n" +
	"\rLaunchRequest\x12\x1e\n" +
	"\vtask_run_id\x18\x01 \x01(\tR\ttaskRunId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\x12=\n" +
	"\x03env\x18\x04 \x03(\v2+.cronova.executor.v1.LaunchRequest.EnvEntryR\x03env\x12'\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\x03R\x0etimeoutSeconds\x12\x19\n" +
	"\blog_path\x18\x06 \x01(\tR\alogPath\x12\x10\n" +
	"\x03dir\x18\a \x01(\tR\x03dir\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\"\n" +
	"\x0eLaunchResponse\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\tR\x03ref\" \n" +
	"\fProbeRequest\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\tR\x03ref\"^\n" +
	"\rProbeResponse\x120\n" +
	"\x05phase\x18\x01 \x01(\x0e2\x1a.cronova.executor.v1.PhaseR\x05phase\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\"!\n" +
	"\rCancelRequest\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\tR\x03ref\" \n" +
	"\x0eCancelResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok*V\n" +
	"\x05Phase\x12\x15\n" +
	"\x11PHASE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rPHASE_RUNNING\x10\x01\x12\x10\n" +
	"\fPHASE_EXITED\x10\x02\x12\x11\n" +
	"\rPHASE_UNKNOWN\x10\x032\x80\x02\n" +
	"\bExecutor\x12Q\n" +
	"\x06Launch\x12\".cronova.executor.v1.LaunchRequest\x1a#.cronova.executor.v1.LaunchResponse\x12N\n" +
	"\x05Probe\x12!.cronova.executor.v1.ProbeRequest\x1a\".cronova.executor.v1.ProbeResponse\x12Q\n" +
	"\x06Cancel\x12\".cronova.executor.v1.CancelRequest\x1a#.cronova.executor.v1.CancelResponseB@Z>github.com/zoyluo/cronova/proto/cronova/executor/v1;executorv1b\x06proto3"

var (
	file_cronova_executor_v1_executor_proto_rawDescOnce sync.Once
	file_cronova_executor_v1_executor_proto_rawDescData []byte
)

func file_cronova_executor_v1_executor_proto_rawDescGZIP() []byte {
	file_cronova_executor_v1_executor_proto_rawDescOnce.Do(func() {
		file_cronova_executor_v1_executor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cronova_executor_v1_executor_proto_rawDesc), len(file_cronova_executor_v1_executor_proto_rawDesc)))
	})
	return file_cronova_executor_v1_executor_proto_rawDescData
}

var file_cronova_executor_v1_executor_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cronova_executor_v1_executor_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_cronova_executor_v1_executor_proto_goTypes = []any{
	(Phase)(0),             // 0: cronova.executor.v1.Phase
	(*LaunchRequest)(nil),  // 1: cronova.executor.v1.LaunchRequest
	(*LaunchResponse)(nil), // 2: cronova.executor.v1.LaunchResponse
	(*ProbeRequest)(nil),   // 3: cronova.executor.v1.ProbeRequest
	(*ProbeResponse)(nil),  // 4: cronova.executor.v1.ProbeResponse
	(*CancelRequest)(nil),  // 5: cronova.executor.v1.CancelRequest
	(*CancelResponse)(nil), // 6: cronova.executor.v1.CancelResponse
	nil,                    // 7: cronova.executor.v1.LaunchRequest.EnvEntry
}
var file_cronova_executor_v1_executor_proto_depIdxs = []int32{
	7, // 0: cronova.executor.v1.LaunchRequest.env:type_name -> cronova.executor.v1.LaunchRequest.EnvEntry
	0, // 1: cronova.executor.v1.ProbeResponse.phase:type_name -> cronova.executor.v1.Phase
	1, // 2: cronova.executor.v1.Executor.Launch:input_type -> cronova.executor.v1.LaunchRequest
	3, // 3: cronova.executor.v1.Executor.Probe:input_type -> cronova.executor.v1.ProbeRequest
	5, // 4: cronova.executor.v1.Executor.Cancel:input_type -> cronova.executor.v1.CancelRequest
	2, // 5: cronova.executor.v1.Executor.Launch:output_type -> cronova.executor.v1.LaunchResponse
	4, // 6: cronova.executor.v1.Executor.Probe:output_type -> cronova.executor.v1.ProbeResponse
	6, // 7: cronova.executor.v1.Executor.Cancel:output_type -> cronova.executor.v1.CancelResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_cronova_executor_v1_executor_proto_init() }
func file_cronova_executor_v1_executor_proto_init() {
	if File_cronova_executor_v1_executor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cronova_executor_v1_executor_proto_rawDesc), len(file_cronova_executor_v1_executor_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cronova_executor_v1_executor_proto_goTypes,
		DependencyIndexes: file_cronova_executor_v1_executor_proto_depIdxs,
		EnumInfos:         file_cronova_executor_v1_executor_proto_enumTypes,
		MessageInfos:      file_cronova_executor_v1_executor_proto_msgTypes,
	}.Build()
	File_cronova_executor_v1_executor_proto = out.File
	file_cronova_executor_v1_executor_proto_goTypes = nil
	file_cronova_executor_v1_executor_proto_depIdxs = nil
}
